# Generated by Django 3.2.18 on 2023-06-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('All platforms', 'All platforms'), ('PC', 'PC'), ('Xbox', 'Xbox'), ('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Xbox Series', 'Xbox Series'), ('PlayStation', 'PlayStation'), ('PlayStation 2', 'PlayStation 2'), ('PlayStation 3', 'PlayStation 3'), ('PlayStation 4', 'PlayStation 4'), ('PlayStation 5', 'PlayStation 5'), ('Nintendo Switch', 'Nintendo Switch'), ('Nintendo Wii', 'Nintendo Wii')], default='All platforms', max_length=20),
        ),
    ]
