# Generated by Django 3.2.18 on 2023-06-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_game_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
