# Generated by Django 3.2.18 on 2023-06-26 13:10

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(condition=models.Q(('title__iexact', django.db.models.expressions.F('title'))), fields=('title',), name='unique_title_case_insensitive'),
        ),
    ]
