# Generated by Django 3.2.18 on 2023-06-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_unique_title_case_insensitive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_title_case_insensitive',
        ),
    ]
